### ISSUE TITLE
[Overview] Docker v1

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#31]
Overview issue for https://github.com/ExchangeUnion/xud-docker/

Global req: All images clean `FROM golang:alpine AS build-stage`

Stage 1:
- [x] [xud only, make things work via simnet, neutrino and ltcd](https://github.com/reliveyy/xud-docker/commit/002ceed6c90ffa620694b987f5ed3d6a28a3e8db)
wait for hold invoice to be stable on simnet for below issues:
- [x] (https://github.com/ExchangeUnion/xud-docker/issues/1)
- [x] (https://github.com/ExchangeUnion/xud-docker/issues/2)

Stage 2 [(`1.0.0-testnet`)](https://github.com/ExchangeUnion/xud-docker/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+project%3AExchangeUnion%2F2):
Setup and connect dependencies as docker images
- [x] BTC: [bitcoind](https://bitcoincore.org/en/download/) + lndbtc
- [x] LTC [litecoind](https://litecoin.org/) + lndltc
- [x] ERC20: partity + raiden
- [x] (https://github.com/ExchangeUnion/xud-docker/issues/5)
- [x] Test regular testnet sync
- [x] xud.sh update mechanism (https://github.com/ExchangeUnion/xud-docker/issues/48)
- [x] `Choose network (simnet/testnet/mainnet):` (https://github.com/ExchangeUnion/xud-docker/issues/52)

answer: `simnet` (`Starting Simnet...`)
answer: `testnet` (`Starting Testnet...`)
answer: `mainnet` (`Not available just yet.`)
- [ ] xud master password (https://github.com/ExchangeUnion/xud-docker/issues/63)

Stage 3 [(`1.0.0-beta`)](https://github.com/ExchangeUnion/xud-docker/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+project%3AExchangeUnion%2F3):
- [ ] choose if the xud system should be started and synced automatically on reboot (https://github.com/ExchangeUnion/xud-docker/issues/15)
- [ ] choose choose coins/tokens one wants to swap.
* ask for pre-existing nodes (https://github.com/ExchangeUnion/xud/issues/891), (TBD: user needs to provide wallet, rpc passwords for these)
- [ ] choose location for backup files (cloud, local network), https://github.com/ExchangeUnion/xud/issues/917
- [ ] choose connection mode (connect to everyone, connect to white-list only). Dependency: https://github.com/ExchangeUnion/xud/issues/179. Needs great explainer.
- [ ] choose channel strategy (multi-hop (autopilot = random channels), [direct channels](https://github.com/ExchangeUnion/xud/issues/909) (only works with white-list atm). Needs great explainer. Difficulties to consider when operating this in production [here](https://github.com/ExchangeUnion/xud/issues/865#issuecomment-479981760). More details tbd

**Comment by kilrau** [comment]
Continuing in https://github.com/ExchangeUnion/xud-docker/issues/30. Closing here.
